[build]
publish = "public"
command = "./stackbit-build.sh"
functions = "./lambda"

  [build.environment]
  HUGO_VERSION = "0.47"

  [[redirects]]
  from = "/posts/*"
  to = "/posts/:splat"
  status = 200
  force = true
  conditions = {Role = ["member"]}
  [[redirects]]
  from = "/posts/*"
  to = "/gated/"
  status = 404
  force = true
